// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC02aCBvltL-mTCUBz9saMxAGLQMRFKO84',
    appId: '1:90210847646:web:bdcf628ca47d0a55db648f',
    messagingSenderId: '90210847646',
    projectId: 'ktf-admin-dev',
    authDomain: 'ktf-admin-dev.firebaseapp.com',
    storageBucket: 'ktf-admin-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1W47VeMqJ68u0RkoJcX4YLo56gj74k10',
    appId: '1:90210847646:android:2c0d6a1316d625d8db648f',
    messagingSenderId: '90210847646',
    projectId: 'ktf-admin-dev',
    storageBucket: 'ktf-admin-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo1hMwvwzkfevKclHk0qi-Nh8roQWTnrE',
    appId: '1:90210847646:ios:c95da63fe5299bafdb648f',
    messagingSenderId: '90210847646',
    projectId: 'ktf-admin-dev',
    storageBucket: 'ktf-admin-dev.appspot.com',
    iosClientId: '90210847646-pt1rkpp5fpsb91rchs6tcvmm4bs0967p.apps.googleusercontent.com',
    iosBundleId: 'com.example.ktfadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo1hMwvwzkfevKclHk0qi-Nh8roQWTnrE',
    appId: '1:90210847646:ios:c95da63fe5299bafdb648f',
    messagingSenderId: '90210847646',
    projectId: 'ktf-admin-dev',
    storageBucket: 'ktf-admin-dev.appspot.com',
    iosClientId: '90210847646-pt1rkpp5fpsb91rchs6tcvmm4bs0967p.apps.googleusercontent.com',
    iosBundleId: 'com.example.ktfadmin',
  );
}
